#!/usr/bin/env tsx
/**
 * Apply migration SQL over the Neon HTTP driver.
 *
 * `prisma migrate deploy` needs a direct TCP connection, which is not reachable from
 * every environment (Neon endpoints resolve IPv6-only). The SQL is still generated by
 * Prisma — `prisma migrate diff` — so the schema remains the single source of truth;
 * only the transport differs.
 *
 * Statements run one at a time because the HTTP driver does not support multi-statement
 * bodies. Already-applied statements are skipped rather than failing the run, so this
 * is safe to re-run.
 */
import 'dotenv/config'
import { readFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'
import { query } from '../src/lib/db/neon'
import { splitStatements } from '../src/lib/db/split-sql'

const MIGRATIONS_DIR = join(process.cwd(), 'prisma', 'migrations')


/**
 * The Neon HTTP driver auto-commits each statement, so it cannot span a transaction.
 * Prisma wraps enum alterations in BEGIN/COMMIT; those markers are dropped here.
 *
 * That is safe only because each statement in such a block is individually valid and
 * idempotent-on-retry for the schema changes we run. It would NOT be safe for a data
 * migration that must be all-or-nothing — those need `prisma migrate deploy` over a
 * direct connection, or an explicit transaction through the WebSocket adapter.
 */
// TRANSACTION_MARKERS now live beside the splitter in src/lib/db/split-sql.ts.

const ALREADY_APPLIED = [
  'already exists',
  'duplicate_object',
  'duplicate_table',
  'duplicate key',
]

async function main() {
  const dirs = readdirSync(MIGRATIONS_DIR).sort()
  let applied = 0
  let skipped = 0

  for (const dir of dirs) {
    const file = join(MIGRATIONS_DIR, dir, 'migration.sql')
    let sql: string
    try {
      sql = readFileSync(file, 'utf8')
    } catch {
      continue
    }

    const statements = splitStatements(sql)
    console.log(`\n${dir}: ${statements.length} statement(s)`)

    for (const statement of statements) {
      try {
        await query(statement)
        applied++
      } catch (error) {
        const message = (error as Error).message.toLowerCase()
        if (ALREADY_APPLIED.some((m) => message.includes(m))) {
          skipped++
          continue
        }
        console.error('\n✗ statement failed:\n', statement.slice(0, 200))
        throw error
      }
    }
  }

  console.log(`\n✓ ${applied} applied, ${skipped} already present`)

  const tables = await query<{ n: string }>(
    "select count(*)::text as n from information_schema.tables where table_schema='public'",
  )
  console.log(`  public tables now: ${tables[0]?.n}`)
}

main().catch((e: Error) => {
  console.error('✗ MIGRATION FAILED:', e.message.split('\n')[0])
  process.exit(1)
})
