import type { UsJurisdictionCode } from '@/lib/compliance/types'

/**
 * Sourced facts for the per-state dyeing guide (see state-dyeing.ts).
 *
 * GENERATED by scripts/state-dyeing-facts.ts from research notes; each fact carries
 * the URL it was checked against. A fact that could not be verified is null, and the
 * page leaves that paragraph out rather than guessing.
 */
export interface StateDyeingFacts {
  readonly waterHardness: 'soft' | 'moderate' | 'hard' | 'very hard' | 'varies' | null
  readonly waterNote: string | null
  readonly waterSource: string | null
  readonly humidity: string | null
  readonly humiditySource: string | null
  readonly sassafrasNative: boolean | null
  readonly sassafrasSource: string | null
  readonly fiberEvents: readonly {
    readonly name: string
    readonly place: string
    readonly month: string | null
    readonly url: string
  }[]
}

export const STATE_DYEING_FACTS: Partial<Record<UsJurisdictionCode, StateDyeingFacts>> = {
  "AK": {
    "waterHardness": "moderate",
    "waterNote": "USGS regional data show mostly moderately hard water, softer in the far north.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "highly variable; cold winters and cool summers",
    "humiditySource": "https://statesummaries.ncics.org/chapter/ak/",
    "sassafrasNative": false,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Fairbanks Fiber Festival",
        "place": "Fairbanks",
        "month": "October",
        "url": "https://www.fairbanksfiberfestival.com/"
      },
      {
        "name": "Fairbanks Weavers & Spinners Guild",
        "place": "Fairbanks",
        "month": null,
        "url": "https://fairbanksweavers.org/"
      },
      {
        "name": "Anchorage Weavers and Spinners Guild",
        "place": "Anchorage",
        "month": null,
        "url": "https://www.anchorageweavespin.org/"
      }
    ]
  },
  "AL": {
    "waterHardness": "soft",
    "waterNote": "USGS regional data put most of Alabama in the soft-water band (under 60 mg/L).",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "hot, humid summers with year-round rain",
    "humiditySource": "https://statesummaries.ncics.org/chapter/al/",
    "sassafrasNative": true,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Alabama Fiber Festival",
        "place": "Birmingham",
        "month": "November",
        "url": "https://www.alfiberfest.com/"
      },
      {
        "name": "Greater Birmingham Fiber Guild",
        "place": "Birmingham area",
        "month": null,
        "url": "https://greaterbirminghamfiberguild.blogspot.com/"
      }
    ]
  },
  "AR": {
    "waterHardness": "soft",
    "waterNote": "USGS regional data show mostly soft to moderately hard water across Arkansas.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "hot, humid summers",
    "humiditySource": "https://statesummaries.ncics.org/chapter/ar/",
    "sassafrasNative": true,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "NWA Fiber Festival",
        "place": "Fayetteville",
        "month": "November",
        "url": "https://www.nwafiberfest.com/"
      },
      {
        "name": "Northwest Arkansas Handweavers Guild",
        "place": "Northwest Arkansas",
        "month": null,
        "url": "https://www.nwahandweaversguild.org/"
      }
    ]
  },
  "AZ": {
    "waterHardness": "very hard",
    "waterNote": "USGS regional data show very hard water (over 180 mg/L) across most of Arizona.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "arid to semiarid, with a summer monsoon",
    "humiditySource": "https://statesummaries.ncics.org/chapter/az/",
    "sassafrasNative": false,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Flagstaff Wool & Fiber Festival",
        "place": "Flagstaff",
        "month": "June",
        "url": "https://www.flagwool.com/"
      },
      {
        "name": "Arizona Fiber Arts Festival (Arizona Federation of Weavers & Spinners Guilds)",
        "place": "Camp Verde",
        "month": "April",
        "url": "https://azfed.org/arizona-fiber-festival/"
      }
    ]
  },
  "CA": {
    "waterHardness": "varies",
    "waterNote": "USGS regional data show soft to moderately hard water in the north and very hard water across Southern California.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "dry summers; wet winters in the north, desert in the southeast",
    "humiditySource": "https://statesummaries.ncics.org/chapter/ca/",
    "sassafrasNative": false,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Lambtown Festival",
        "place": "Dixon",
        "month": "October",
        "url": "https://www.lambtown.org/"
      },
      {
        "name": "Fibershed",
        "place": "Point Reyes Station",
        "month": null,
        "url": "https://fibershed.org/"
      }
    ]
  },
  "CO": {
    "waterHardness": "very hard",
    "waterNote": "USGS regional data show very hard water across much of Colorado; local supplies vary.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "semiarid, generally dry",
    "humiditySource": "https://statesummaries.ncics.org/chapter/co/",
    "sassafrasNative": false,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Estes Park Wool Market",
        "place": "Estes Park",
        "month": "June",
        "url": "https://www.visitestespark.com/events-calendar/summer-events/wool-market/"
      },
      {
        "name": "Rocky Mountain Weavers Guild",
        "place": "Denver",
        "month": null,
        "url": "https://www.rmwg.org/"
      }
    ]
  },
  "CT": {
    "waterHardness": "soft",
    "waterNote": "USGS regional data put Connecticut in the soft-water band.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "cold, snowy winters and warm, humid summers",
    "humiditySource": "https://statesummaries.ncics.org/chapter/ct/",
    "sassafrasNative": true,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "CT Sheep, Wool & Fiber Festival",
        "place": "North Haven",
        "month": "April",
        "url": "https://ctsheep.com/ct-sheep-wool-fiber-festival/"
      },
      {
        "name": "Handweavers' Guild of Connecticut",
        "place": "South Glastonbury",
        "month": null,
        "url": "https://www.handweaversguildofct.org/"
      }
    ]
  },
  "DC": {
    "waterHardness": "moderate",
    "waterNote": "USGS regional data show soft to moderately hard water around the Potomac and the Washington area.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "warm, humid summers",
    "humiditySource": "https://statesummaries.ncics.org/chapter/md/",
    "sassafrasNative": true,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": []
  },
  "DE": {
    "waterHardness": "soft",
    "waterNote": "USGS regional data show soft to moderately hard water in Delaware.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "cold winters and warm summers, Atlantic-moderated",
    "humiditySource": "https://statesummaries.ncics.org/chapter/de/",
    "sassafrasNative": true,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Harmony Weavers Guild",
        "place": "Wilmington",
        "month": null,
        "url": "https://harmonyweaversguild.org/"
      }
    ]
  },
  "FL": {
    "waterHardness": "varies",
    "waterNote": "USGS regional data show soft water in the Panhandle and north, and hard to very hard water down the peninsula.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "hot, humid summers and mild winters",
    "humiditySource": "https://statesummaries.ncics.org/chapter/fl/",
    "sassafrasNative": true,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Florida Fiber In",
        "place": "Kissimmee",
        "month": "September",
        "url": "https://floridafiberin.com/"
      }
    ]
  },
  "GA": {
    "waterHardness": "soft",
    "waterNote": "USGS regional data put most of Georgia in the soft-water band.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "long, hot and humid summers",
    "humiditySource": "https://statesummaries.ncics.org/chapter/ga/",
    "sassafrasNative": true,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Chattahoochee Handweavers Guild",
        "place": "Atlanta",
        "month": null,
        "url": "https://chgweavers.org/"
      },
      {
        "name": "Athens Fibercraft Guild",
        "place": "Athens",
        "month": null,
        "url": "https://athensfiber.org/"
      }
    ]
  },
  "HI": {
    "waterHardness": "soft",
    "waterNote": "USGS regional data put the Hawaiian Islands in the soft-water band.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "tropical, with a November–April wet season",
    "humiditySource": "https://statesummaries.ncics.org/chapter/hi/",
    "sassafrasNative": false,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Hawaii Handweavers' Hui",
        "place": "Honolulu",
        "month": null,
        "url": "https://hawaiihandweavers.org/"
      },
      {
        "name": "Fiber Hawai'i, the Hawai'i Craftsmen fiber exhibition",
        "place": "statewide",
        "month": null,
        "url": "https://hawaiicraftsmen.wildapricot.org/fiber2026"
      }
    ]
  },
  "IA": {
    "waterHardness": "hard",
    "waterNote": "USGS regional data show hard to very hard water across Iowa.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "wide temperature swings; humid summers",
    "humiditySource": "https://statesummaries.ncics.org/chapter/ia/",
    "sassafrasNative": true,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Shepherds Market",
        "place": "Iowa City",
        "month": "March",
        "url": "https://www.shepherds-market-iowa.net/"
      },
      {
        "name": "Des Moines Weavers & Spinners Guild",
        "place": "Des Moines",
        "month": null,
        "url": "https://www.desmoinesweaversguild.org/"
      }
    ]
  },
  "ID": {
    "waterHardness": "varies",
    "waterNote": "USGS regional data show moderately hard water in the north and hard water across the south.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "cold winters and dry, warm summers in the south",
    "humiditySource": "https://statesummaries.ncics.org/chapter/id/",
    "sassafrasNative": false,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Trailing of the Sheep Festival (Wool Fest)",
        "place": "Hailey and Ketchum",
        "month": "October",
        "url": "https://trailingofthesheep.org/wool-fest/"
      }
    ]
  },
  "IL": {
    "waterHardness": "hard",
    "waterNote": "USGS regional data show hard water across most of Illinois, very hard in places.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "cold winters and humid summers",
    "humiditySource": "https://statesummaries.ncics.org/chapter/il/",
    "sassafrasNative": true,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Illinois Fiber Festival",
        "place": "Bloomington",
        "month": "March",
        "url": "https://illinoisfiberfestival.substack.com/p/illinois-fiber-festival"
      },
      {
        "name": "Champaign-Urbana Spinners & Weavers Guild",
        "place": "Champaign",
        "month": null,
        "url": "https://cuswg.org/"
      }
    ]
  },
  "IN": {
    "waterHardness": "hard",
    "waterNote": "USGS regional data show hard water across most of Indiana, very hard in places.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "cold winters and humid summers",
    "humiditySource": "https://statesummaries.ncics.org/chapter/in/",
    "sassafrasNative": true,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Hoosier Hills Fiber Festival",
        "place": "Franklin",
        "month": "June",
        "url": "https://www.hoosierhillsfiberfestival.com/"
      }
    ]
  },
  "KS": {
    "waterHardness": "very hard",
    "waterNote": "USGS regional data show very hard water across most of Kansas.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "humid in the east, semiarid in the west",
    "humiditySource": "https://statesummaries.ncics.org/chapter/ks/",
    "sassafrasNative": true,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Fiber Flurry",
        "place": "Leonardville",
        "month": "November",
        "url": "https://fiberflurry.com/"
      },
      {
        "name": "Kansas Alliance of Weavers and Spinners",
        "place": "Statewide",
        "month": null,
        "url": "https://www.kansasweaversspinners.com/"
      }
    ]
  },
  "KY": {
    "waterHardness": "moderate",
    "waterNote": "USGS regional data show mostly moderately hard water in Kentucky, harder in places.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "hot, humid summers and abundant rain",
    "humiditySource": "https://statesummaries.ncics.org/chapter/ky/",
    "sassafrasNative": true,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Kentucky Sheep and Fiber Festival",
        "place": "Lexington",
        "month": "May",
        "url": "https://www.kentuckysheepandfiber.com/"
      }
    ]
  },
  "LA": {
    "waterHardness": "soft",
    "waterNote": "USGS regional data show mostly soft to moderately hard water in Louisiana.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "hot summers, mild winters, year-round rain",
    "humiditySource": "https://statesummaries.ncics.org/chapter/la/",
    "sassafrasNative": true,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "New Orleans Weavers Guild",
        "place": "New Orleans",
        "month": null,
        "url": "https://www.nowg.org/"
      }
    ]
  },
  "MA": {
    "waterHardness": "soft",
    "waterNote": "USGS regional data put Massachusetts in the soft-water band.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "cold, snowy winters and warm summers",
    "humiditySource": "https://statesummaries.ncics.org/chapter/ma/",
    "sassafrasNative": true,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Fiber Festival of New England",
        "place": "West Springfield",
        "month": "November",
        "url": "https://www.easternstatesexposition.com/p/fiberfestival"
      },
      {
        "name": "Weavers' Guild of Boston",
        "place": "Westborough",
        "month": null,
        "url": "https://www.weaversguildofboston.org/"
      }
    ]
  },
  "MD": {
    "waterHardness": "soft",
    "waterNote": "USGS regional data show soft to moderately hard water across Maryland.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "warm, humid summers",
    "humiditySource": "https://statesummaries.ncics.org/chapter/md/",
    "sassafrasNative": true,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Maryland Sheep & Wool Festival",
        "place": "West Friendship",
        "month": "May",
        "url": "https://sheepandwool.org/"
      },
      {
        "name": "Weavers Guild of Greater Baltimore",
        "place": "Ellicott City",
        "month": null,
        "url": "https://wggb.org/"
      }
    ]
  },
  "ME": {
    "waterHardness": "soft",
    "waterNote": "USGS regional data put Maine in the soft-water band.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "cold, snowy winters and mild summers",
    "humiditySource": "https://statesummaries.ncics.org/chapter/me/",
    "sassafrasNative": true,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Maine Fiber Frolic",
        "place": "Windsor",
        "month": "June",
        "url": "https://fiberfrolic.com/"
      },
      {
        "name": "Common Ground Country Fair",
        "place": "Unity",
        "month": "September",
        "url": "https://www.mofga.org/whats-at-the-fair/"
      }
    ]
  },
  "MI": {
    "waterHardness": "varies",
    "waterNote": "USGS regional data show moderately hard water in the Upper Peninsula and hard water across most of the Lower Peninsula.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "warm, humid summers and cold winters",
    "humiditySource": "https://statesummaries.ncics.org/chapter/mi/",
    "sassafrasNative": true,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Michigan Fiber Festival",
        "place": "Allegan",
        "month": "August",
        "url": "https://www.michiganfiberfestival.info/"
      },
      {
        "name": "Michigan League of Handweavers",
        "place": "Statewide",
        "month": null,
        "url": "https://mlhguild.org/"
      }
    ]
  },
  "MN": {
    "waterHardness": "varies",
    "waterNote": "USGS regional data show moderately hard water in the northeast and hard to very hard water in the south and west.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "humid east, drier west; humid summers",
    "humiditySource": "https://statesummaries.ncics.org/chapter/mn/",
    "sassafrasNative": false,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Shepherd's Harvest Sheep & Wool Festival",
        "place": "Lake Elmo",
        "month": "May",
        "url": "https://shepherdsharvestfestival.org/"
      },
      {
        "name": "Weavers Guild of Minnesota",
        "place": "Minneapolis",
        "month": null,
        "url": "https://www.weaversguildmn.org/"
      }
    ]
  },
  "MO": {
    "waterHardness": "varies",
    "waterNote": "USGS regional data show hard water in the north and moderately hard water in the south.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "warm, moist summers with rising humidity",
    "humiditySource": "https://statesummaries.ncics.org/chapter/mo/",
    "sassafrasNative": true,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Lake Area Fiber Arts Festival",
        "place": "Camdenton",
        "month": "October",
        "url": "https://www.lakefiberarts.com/"
      },
      {
        "name": "Weavers' Guild of St. Louis",
        "place": "St. Louis",
        "month": null,
        "url": "https://weaversguildstl.org/"
      }
    ]
  },
  "MS": {
    "waterHardness": "soft",
    "waterNote": "USGS regional data put most of Mississippi in the soft-water band.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "hot summers, mild winters, year-round rain",
    "humiditySource": "https://statesummaries.ncics.org/chapter/ms/",
    "sassafrasNative": true,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Chimneyville Weavers and Spinners Guild",
        "place": "Jackson",
        "month": null,
        "url": "https://www.cvillewsg.com/"
      }
    ]
  },
  "MT": {
    "waterHardness": "varies",
    "waterNote": "USGS regional data show moderately hard water in the western mountains and hard to very hard water on the eastern plains.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "dry air; cold winters",
    "humiditySource": "https://statesummaries.ncics.org/chapter/mt/",
    "sassafrasNative": false,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Montana Association of Weavers & Spinners",
        "place": "Statewide (conference location rotates)",
        "month": null,
        "url": "https://www.montanaweavespin.org/"
      },
      {
        "name": "Missoula Weavers Guild",
        "place": "Missoula",
        "month": null,
        "url": "https://missoulaweaversguild.org/"
      }
    ]
  },
  "NC": {
    "waterHardness": "soft",
    "waterNote": "USGS regional data put North Carolina in the soft-water band.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "humid, with very warm summers",
    "humiditySource": "https://statesummaries.ncics.org/chapter/nc/",
    "sassafrasNative": true,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Southeastern Animal Fiber Fair (SAFF)",
        "place": "Fletcher",
        "month": "October",
        "url": "https://saffsite.org/"
      },
      {
        "name": "Carolina FiberFest",
        "place": "Raleigh",
        "month": "March",
        "url": "https://carolinafiberfest.org/"
      }
    ]
  },
  "ND": {
    "waterHardness": "hard",
    "waterNote": "USGS regional data show hard to very hard water across North Dakota.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "moist east, semiarid west",
    "humiditySource": "https://statesummaries.ncics.org/chapter/nd/",
    "sassafrasNative": false,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": []
  },
  "NE": {
    "waterHardness": "hard",
    "waterNote": "USGS regional data show hard to very hard water across most of Nebraska.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "humid east, semiarid west",
    "humiditySource": "https://statesummaries.ncics.org/chapter/ne/",
    "sassafrasNative": false,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Omaha Weavers and Spinners Guild",
        "place": "Omaha",
        "month": null,
        "url": "https://owsguild.com/"
      },
      {
        "name": "Hand Weavers Guild of Lincoln",
        "place": "Lincoln",
        "month": null,
        "url": "https://lincolnweavers.org/"
      }
    ]
  },
  "NH": {
    "waterHardness": "soft",
    "waterNote": "USGS regional data put New Hampshire in the soft-water band.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "cold, snowy winters and mild summers",
    "humiditySource": "https://statesummaries.ncics.org/chapter/nh/",
    "sassafrasNative": true,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "New Hampshire Sheep & Wool Festival",
        "place": "Deerfield",
        "month": "May",
        "url": "https://nhswga.org/nh-sheep-wool-festival/"
      }
    ]
  },
  "NJ": {
    "waterHardness": "soft",
    "waterNote": "USGS regional data put most of New Jersey in the soft-water band.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "warm, humid summers",
    "humiditySource": "https://statesummaries.ncics.org/chapter/nj/",
    "sassafrasNative": true,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Garden State Sheep Breeders Sheep & Fiber Festival",
        "place": "Ringoes",
        "month": "September",
        "url": "https://njsheep.net/"
      },
      {
        "name": "Frances Irwin Handweavers",
        "place": "Northwestern New Jersey",
        "month": null,
        "url": "https://www.francesirwinhandweavers.org/"
      }
    ]
  },
  "NM": {
    "waterHardness": "very hard",
    "waterNote": "USGS regional data show very hard water across most of New Mexico.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "arid to semiarid",
    "humiditySource": "https://statesummaries.ncics.org/chapter/nm/",
    "sassafrasNative": false,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Taos Wools Festival",
        "place": "Taos",
        "month": "October",
        "url": "https://taoswoolsfestival.com/"
      },
      {
        "name": "Las Arañas Spinners & Weavers Guild",
        "place": "Albuquerque",
        "month": null,
        "url": "https://lasaranasguild.org/"
      }
    ]
  },
  "NV": {
    "waterHardness": "varies",
    "waterNote": "USGS regional data show hard water in the north and very hard water in the south.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "largely dry",
    "humiditySource": "https://statesummaries.ncics.org/chapter/nv/",
    "sassafrasNative": false,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Las Vegas Fiber Arts Guild",
        "place": "Las Vegas",
        "month": null,
        "url": "https://fiberartsguildlv.org/"
      },
      {
        "name": "Reno Fiber Guild",
        "place": "Reno",
        "month": null,
        "url": "http://renofiberguild.blogspot.com/"
      }
    ]
  },
  "NY": {
    "waterHardness": "varies",
    "waterNote": "USGS regional data show soft water in the east and Adirondacks and hard to very hard water in western New York.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "cold, snowy winters; moist Atlantic and Great Lakes air",
    "humiditySource": "https://statesummaries.ncics.org/chapter/ny/",
    "sassafrasNative": true,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "New York State Sheep & Wool Festival",
        "place": "Rhinebeck",
        "month": "October",
        "url": "https://sheepandwool.com/"
      },
      {
        "name": "Shepherd's Wool Market (Genesee Valley Handspinners Guild)",
        "place": "Rush",
        "month": "May",
        "url": "https://gvhg.org/shepherds-wool-market/"
      }
    ]
  },
  "OH": {
    "waterHardness": "hard",
    "waterNote": "USGS regional data show hard water across most of Ohio, very hard in parts of the west.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "cold winters and humid summers",
    "humiditySource": "https://statesummaries.ncics.org/chapter/oh/",
    "sassafrasNative": true,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Great Lakes Fiber Show",
        "place": "Wooster",
        "month": "May",
        "url": "https://greatlakesfibershow.org/"
      },
      {
        "name": "Lorain County Spinners and Weavers Guild",
        "place": "Lorain County",
        "month": null,
        "url": "https://locoguild.com/"
      }
    ]
  },
  "OK": {
    "waterHardness": "varies",
    "waterNote": "USGS regional data show very hard water in the west and hard water in the east.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "humid southeast, semiarid west",
    "humiditySource": "https://statesummaries.ncics.org/chapter/ok/",
    "sassafrasNative": true,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Fiber Christmas in July",
        "place": "Kellyville",
        "month": "July",
        "url": "https://fiberchristmas.com/"
      },
      {
        "name": "Weavers Guild of Oklahoma City",
        "place": "Del City",
        "month": null,
        "url": "https://www.weaversguildokc.com/"
      }
    ]
  },
  "OR": {
    "waterHardness": "varies",
    "waterNote": "USGS regional data show soft water west of the Cascades and harder water in the southeast.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "wet west of the Cascades, much drier east",
    "humiditySource": "https://statesummaries.ncics.org/chapter/or/",
    "sassafrasNative": false,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Black Sheep Gathering",
        "place": "Albany",
        "month": "June",
        "url": "https://blacksheepgathering.org/"
      },
      {
        "name": "Oregon Flock & Fiber Festival",
        "place": "Albany",
        "month": "October",
        "url": "https://www.oregonflockandfiberfestival.com/"
      }
    ]
  },
  "PA": {
    "waterHardness": "varies",
    "waterNote": "USGS regional data show soft to moderately hard water in the east and harder water in parts of the west.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "moist; humid summer heat in the southeast",
    "humiditySource": "https://statesummaries.ncics.org/chapter/pa/",
    "sassafrasNative": true,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Central Pennsylvania Fiber Festival",
        "place": "Hughesville",
        "month": "May",
        "url": "https://centralpennfiberfest.com/"
      },
      {
        "name": "Sheep & Fiber Festival",
        "place": "Waynesburg",
        "month": "May",
        "url": "https://waynesburgpa.org/Events/sheepinfo.html"
      }
    ]
  },
  "RI": {
    "waterHardness": "soft",
    "waterNote": "USGS regional data put Rhode Island in the soft-water band.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "moist Atlantic air; about 46 inches of rain a year",
    "humiditySource": "https://statesummaries.ncics.org/chapter/ri/",
    "sassafrasNative": true,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Sheep & Wool Festival at Coggeshall Farm Museum",
        "place": "Bristol",
        "month": "May",
        "url": "https://coggeshallfarm.org/event/sheep-wool-festival/"
      },
      {
        "name": "Weavers Guild of Rhode Island",
        "place": "North Kingstown",
        "month": null,
        "url": "https://wgri.org/"
      }
    ]
  },
  "SC": {
    "waterHardness": "soft",
    "waterNote": "USGS regional data put South Carolina in the soft-water band.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "humid, with hot summers",
    "humiditySource": "https://statesummaries.ncics.org/chapter/sc/",
    "sassafrasNative": true,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Carolina Spinners, Weavers, and Knitters Guild",
        "place": "Camden",
        "month": null,
        "url": "https://spinweaveknitsc.com/"
      }
    ]
  },
  "SD": {
    "waterHardness": "very hard",
    "waterNote": "USGS regional data show hard to very hard water across South Dakota.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "moist east, semiarid west",
    "humiditySource": "https://statesummaries.ncics.org/chapter/sd/",
    "sassafrasNative": false,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "North Country Fiber Fair",
        "place": "Watertown",
        "month": "September",
        "url": "https://northcountryfiberfair.org/"
      },
      {
        "name": "Crossthreads Fiberworks Guild",
        "place": "Sioux Falls",
        "month": null,
        "url": "https://www.crossthreadsfiberguild.com/"
      }
    ]
  },
  "TN": {
    "waterHardness": "varies",
    "waterNote": "USGS regional data show soft water in the east and moderately hard to hard water in Middle and West Tennessee.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "warm, humid summers",
    "humiditySource": "https://statesummaries.ncics.org/chapter/tn/",
    "sassafrasNative": true,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Middle Tennessee Fiber Festival",
        "place": "Dickson",
        "month": null,
        "url": "https://tnfiberfestival.com/"
      },
      {
        "name": "Tennessee Valley Handspinners Guild",
        "place": "Knoxville",
        "month": null,
        "url": "https://tnvalleyhandspinners.org/"
      }
    ]
  },
  "TX": {
    "waterHardness": "varies",
    "waterNote": "USGS regional data show very hard water in the west and center and softer water in East Texas.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "hot summers; humid east, dry west",
    "humiditySource": "https://statesummaries.ncics.org/chapter/tx/",
    "sassafrasNative": true,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "DFW Fiber Fest",
        "place": "Irving",
        "month": null,
        "url": "https://dfwfiberfest.org/"
      },
      {
        "name": "Contemporary Handweavers of Texas",
        "place": "Statewide",
        "month": null,
        "url": "https://weavetexas.org/"
      }
    ]
  },
  "UT": {
    "waterHardness": "very hard",
    "waterNote": "USGS regional data show very hard water across most of Utah.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "semiarid; mostly dry",
    "humiditySource": "https://statesummaries.ncics.org/chapter/ut/",
    "sassafrasNative": false,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Great Basin Fiber Arts Fair",
        "place": "Farmington",
        "month": "April",
        "url": "https://www.gbfaf.org/"
      },
      {
        "name": "Mary Meigs Atwater Weavers Guild of Utah",
        "place": "Salt Lake City area",
        "month": null,
        "url": "https://www.mmawg.org/"
      }
    ]
  },
  "VA": {
    "waterHardness": "soft",
    "waterNote": "USGS regional data show soft water across most of Virginia, moderately hard in the west.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "humid, with very warm summers",
    "humiditySource": "https://statesummaries.ncics.org/chapter/va/",
    "sassafrasNative": true,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Shenandoah Valley Fiber Festival",
        "place": "Berryville",
        "month": "September",
        "url": "https://svfiberfestival.com/"
      },
      {
        "name": "Fall Fiber Festival & Montpelier Sheep Dog Trials",
        "place": "Montpelier Station",
        "month": "October",
        "url": "https://fallfiberfestival.org/"
      }
    ]
  },
  "VT": {
    "waterHardness": "soft",
    "waterNote": "USGS regional data put Vermont in the soft-water band.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "cold, snowy winters and warm summers",
    "humiditySource": "https://statesummaries.ncics.org/chapter/vt/",
    "sassafrasNative": true,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Vermont Sheep & Wool Festival",
        "place": "Tunbridge",
        "month": "October",
        "url": "https://vtsheepandwoolfest.com/"
      },
      {
        "name": "Vermont Weavers Guild",
        "place": "Randolph",
        "month": null,
        "url": "https://www.vermontweaversguild.org/"
      }
    ]
  },
  "WA": {
    "waterHardness": "varies",
    "waterNote": "USGS regional data show soft water west of the Cascades and moderately hard water to the east.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "wet west of the Cascades, drier east",
    "humiditySource": "https://statesummaries.ncics.org/chapter/wa/",
    "sassafrasNative": false,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Shepherd's Extravaganza",
        "place": "Enumclaw",
        "month": "April",
        "url": "https://shepherds-extravaganza.com/"
      },
      {
        "name": "Whidbey Weavers Guild",
        "place": "Coupeville",
        "month": null,
        "url": "https://whidbeyweaversguild.org/"
      }
    ]
  },
  "WI": {
    "waterHardness": "varies",
    "waterNote": "USGS regional data show moderately hard water in the north and hard water in the south.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "cold winters; humid summer air masses",
    "humiditySource": "https://statesummaries.ncics.org/chapter/wi/",
    "sassafrasNative": false,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Wisconsin Sheep & Wool Festival",
        "place": "Jefferson",
        "month": "September",
        "url": "https://wisconsinsheepandwoolfestival.com/"
      },
      {
        "name": "Wisconsin Handweavers Inc.",
        "place": "Milwaukee",
        "month": null,
        "url": "https://www.wihandweavers.org/"
      }
    ]
  },
  "WV": {
    "waterHardness": "moderate",
    "waterNote": "USGS regional data show soft to moderately hard water across West Virginia.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "warm, humid summers",
    "humiditySource": "https://statesummaries.ncics.org/chapter/wv/",
    "sassafrasNative": true,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "West Virginia Fiber Festival",
        "place": "Morgantown",
        "month": "September",
        "url": "https://westvirginiafiberfestival.com/"
      }
    ]
  },
  "WY": {
    "waterHardness": "very hard",
    "waterNote": "USGS regional data show hard to very hard water across Wyoming.",
    "waterSource": "https://www.usgs.gov/special-topics/water-science-school/science/hardness-water",
    "humidity": "mostly semiarid",
    "humiditySource": "https://statesummaries.ncics.org/chapter/wy/",
    "sassafrasNative": false,
    "sassafrasSource": "http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501217",
    "fiberEvents": [
      {
        "name": "Wyoming Sheep & Wool Festival",
        "place": "Location rotates (Powell in 2026)",
        "month": null,
        "url": "https://www.wyomingsheepandwoolfestival.com/"
      }
    ]
  }
}
